<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?= $this->translate('Page not found') ?></title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>
<body>
<div id="container">
	<div id="notFound">
		<h1>Page not found</h1>
	</div>
	<? if (isset($this->exception)): ?>
	<div id="exception">
		<h3>Exception information:</h3>
		<p>
			<bstrong>Message:</strong> <?php echo $this->exception->getMessage() ?>
		</p>
	
		<h3>Stack trace:</h3>
		<pre><?php echo $this->exception->getTraceAsString() ?></pre>
	
		<h3>Request Parameters:</h3>
		<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
	</div>
	<? endif ?>
</div>
</body>