<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?= $this->translate('Page not found') ?></title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>
<body>
	<div id="container">
		<div id="header">
			<p class="navigation">
				<a href="<?= $this->url(array('action' => 'index', 'controller' => 'index'), 'default', true) ?>">Home</a> | 
				<a href="<?= $this->url(array('action' => 'index', 'controller' => 'index', 'module' => 'admin'), 'default', true) ?>">Admin</a>
			</p>
		</div>
		<div id="content">
			<?= $this->layout()->content ?>
		</div>
		<div id="footer">
		</div>
	</div>
</body>