<table style="border: 1px solid;">
	<tr>
		<td colspan="3"><a href="<?= $this->url(array('action' => 'add', 'controller' => 'labels', 'module' => 'admin'), 'default', true) ?>">Add new</a></td>
	</tr>
	<? foreach($this->labels as $label) : ?>
	<tr>
		<td><?= $label->text ?></td>
		<td><a href="<?= $this->url(array('id' => $label->id, 'action' => 'update', 'controller' => 'labels', 'module' => 'admin'), 'default', true) ?>">update</a></td>
		<td><a href="<?= $this->url(array('id' => $label->id, 'action' => 'delete', 'controller' => 'labels', 'module' => 'admin'), 'default', true) ?>">delete</a></td>
	</tr>
	<? endforeach ?>
	<tr>
		<td colspan="3"><a href="<?= $this->url(array('action' => 'add', 'controller' => 'labels', 'module' => 'admin'), 'default', true) ?>">Add new</a></td>
	</tr>
</table>